site_name: Happyfeet Application Docs
docs_dir: docs
theme:
  name: material
nav:
  - Home: index.md
  - Domain Overview: domain-overview.md
  - Business Capability Model: business-capability-model.md
  - Organization Model: organization-model.md
  - Business Processes: business-processes.md
  - Business Rules: business-rules.md
  - Domain Model: domain-model.md
  - Domain Glossary: domain-glossary.md
